version: '3.9'

services:
  django:
    build: .
    container_name: django
    command:
#      - python manage.py migrate
#      - python manage.py create_group
      - python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./crm_backoffice:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=crm_db
    volumes:
      - crm_db_data:/var/lib/postgresql/data
    networks:
      - backend


networks:
  backend:
    driver: bridge

volumes:
  crm_db_data: {}