version: '3.9'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=crm_db
    volumes:
      - crm_db_data:/var/lib/postgresql/data

volumes:
  crm_db_data: {}