# Generated by Django 5.0 on 2024-01-16 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoleUser',
        ),
    ]
