# Generated by Django 5.0 on 2023-12-31 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("office", "0003_remove_customer_email_remove_customer_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="office.lead"
            ),
        ),
    ]
