# Generated by Django 5.0 on 2023-12-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("office", "0004_alter_customer_lead"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
