# Generated by Django 5.0 on 2023-12-31 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("office", "0006_ads"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="ads",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="office.ads"
            ),
        ),
    ]
