# Generated by Django 5.0 on 2023-12-31 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("office", "0007_lead_ads"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="office.lead"
            ),
        ),
    ]
