# Generated by Django 5.0 on 2023-12-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("office", "0008_alter_customer_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="ads",
            name="customers_count",
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="ads",
            name="leads_count",
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
