# Generated by Django 5.0 on 2024-01-01 06:14

import django.db.models.deletion
import office.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("office", "0009_ads_customers_count_ads_leads_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ads",
            name="customers_count",
        ),
        migrations.RemoveField(
            model_name="ads",
            name="leads_count",
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "file",
                    models.FileField(upload_to=office.models.upload_directory_path),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="office.product"
                    ),
                ),
            ],
        ),
    ]
