# Generated by Django 5.0 on 2024-01-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("office", "0010_remove_ads_customers_count_remove_ads_leads_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="contract",
            name="start_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
