# Generated by Django 5.0 on 2024-01-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("office", "0011_alter_contract_end_date_alter_contract_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="start_date",
            field=models.DateField(auto_now=True),
        ),
    ]
