# Generated by Django 5.0 on 2024-01-01 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("office", "0013_alter_contract_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="office.contract",
            ),
        ),
    ]
