# Generated by Django 5.0 on 2024-01-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("office", "0014_customer_contract"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
