# Generated by Django 5.0 on 2024-02-28 08:27

import django.db.models.deletion
import office.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0015_alter_lead_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.product'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, upload_to=office.models.upload_directory_path),
        ),
        migrations.AlterField(
            model_name='contract',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.product'),
        ),
    ]
